sonar.projectKey=Flask_Image_Recognition
sonar.projectName=Flask Image Recognition
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/test_*.py,**/*_test.py,**/conftest.py

sonar.exclusions=**/tests/**,**/test_*.py,**/*_test.py,**/__pycache__/**,**/.venv/**,**/venv/**,**/*.md,**/*.txt,**/.github/**,**/templates/**,**/static/**

sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml

sonar.scm.provider=git
