name: Python CI (pre-commit + pytest)

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install project deps
        run: |
          pip install -r requirements.txt
          pip install pytest pre-commit pylint

      # Phase 2: linting demonstarion but doesn't block the build
      - name: Run pre-commit (lint hooks)
        run: pre-commit run --all-files --show-diff-on-failure
        continue-on-error: true

      # Run tests. If model assets aren't present in CI, skip model tests only.
      - name: Run pytest (auto-skip model tests if assets missing)
        env:
          PYTHONPATH: .
        run: |
          if [ -f digit_model.h5 ]; then
            echo "digit_model.h5 found → running full test suite"
            pytest -q
          else
            echo "digit_model.h5 not found → running all tests except model tests"
            pytest -q -k "not test_model"
          fi
